mysql:
  username: newsr_user
  password: passwd
  db_name: newsr

google:
  news-url: https://news.google.com/news?hl=en-US&ceid=US:en&sort=date&gl=US&num=10&output=rss&q=
  date-time-layout: Mon, 02 Jan 2006 15:04:05 MST
  keyword: covid

worker-count: 8
